@startuml

skinparam linetype ortho
skinparam packageStyle rectangle

class auth.AuthUserDetailsService {
  - UserAuthPort userAuthPort
  + UserDetails loadUserByUsername(String)
}

class auth.SecurityConfig {
  - SecurityFilter securityFilter
  + SecurityFilterChain filterChain(HttpSecurity)
  + AuthenticationManager authenticationManager(AuthenticationConfiguration)
  + PasswordEncoder passwordEncoder()
  + CorsConfigurationSource corsConfigurationSource()
}

interface auth.UserAuthPort {
  ~ Optional<AuthUserData> findByEmail(String)
}

class auth.AuthController {
  - AuthService authService
  + ResponseEntity<TokenResponse> login(LoginRequest, HttpServletResponse)
}

class auth.AuthUserDetails {
  - AuthUserData data
  + Collection<? extends GrantedAuthority> getAuthorities()
  + String getPassword()
  + String getUsername()
  + boolean isEnabled()
}

class auth.AuthService {
  - AuthenticationManager authenticationManager
  - JwtService jwtService
  + TokenResponse login(LoginRequest)
}

class auth.JwtService {
  - String secret
  - int expirationHours
  + String generateToken(String)
  + String extractUsername(String)
  + boolean isTokenValid(String)
}

class auth.LoginRequest {
  - String email
  - String password
}

class auth.TokenResponse {
  - String token
  - UUID id
  - String name
  - String email
  - String role
  - Boolean isActive
  - LocalDateTime createdAt
  - LocalDateTime updatedAt
  - LocalDateTime deletedAt
}

class auth.SecurityFilter {
  - JwtService jwtService
  - UserAuthPort userAuthPort
  # void doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
}

class auth.AuthUserData {
  - UUID id
  - String name
  - String email
  - String encodedPassword
  - String role
  - Boolean isActive
  - LocalDateTime createdAt
  - LocalDateTime updatedAt
  - LocalDateTime deletedAt
}

' Herança / Implementação
org.springframework.security.core.userdetails.UserDetailsService <|.. auth.AuthUserDetailsService
org.springframework.security.core.userdetails.UserDetails <|.. auth.AuthUserDetails
org.springframework.web.filter.OncePerRequestFilter <|-- auth.SecurityFilter

' Composição
auth.AuthUserDetails *-- auth.AuthUserData

' Dependências por campo (injeção)
auth.AuthUserDetailsService --> auth.UserAuthPort
auth.SecurityConfig --> auth.SecurityFilter
auth.AuthController --> auth.AuthService
auth.AuthService --> auth.JwtService
auth.SecurityFilter --> auth.JwtService
auth.SecurityFilter --> auth.UserAuthPort

' Uso (parâmetros e retornos de métodos)
auth.AuthController ..> auth.LoginRequest
auth.AuthController ..> auth.TokenResponse
auth.AuthService ..> auth.LoginRequest
auth.AuthService ..> auth.TokenResponse
auth.AuthUserDetailsService ..> auth.AuthUserDetails
auth.UserAuthPort ..> auth.AuthUserData

@enduml
